apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
    - name: hello-client
      image: hello-client:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9090
      env:
        - name: SERVER_URL
          value: 'http://$(SERVER_SERVICE_HOST):$(SERVER_SERVICE_PORT)'