apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    my-name: server
spec:
  containers:
    - name: hello-server
      image: hello-server:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
